### ISSUE TITLE
Part List 

### ISSUE THREAD

**Issue by ATOG2074** [toto99303/Prusa-MK2-Ext.-Driver-Board#1]
I know i'm a little late to the party only i did not use my printer a lot because of the noise it makes now i found this GitHub 

now i can order 5 PCB's at PCBWay for only 10euro i don't know what parts i need to solder on the board is there a list so i can order the parts.

- Connectors 
- Capacitors 
- Resistors

**Comment by ghost** [comment]
As far as I can tell:

* 2 x 10k Ohm resistor 
* 2 x 100uF capacitors
* Molex connector
* Pheonix power connector

**Comment by toto99303** [comment]
Hello, sorry for the late reply, I've added a BOM to the main readme page. Have fun!

**Comment by toto99303** [comment]
Closing.

**Comment by toto99303** [comment]
Hello, sorry for the late reply, I've added a BOM to the main readme page. Have fun!
