### ISSUE TITLE
Selling PCB Boards

### ISSUE THREAD

**Issue by ghost** [toto99303/Prusa-MK2-Ext.-Driver-Board#2]
Hi there,

not sure if this is the right 'forum' for this, but I have ordered a couple of PCBs based on the latest version.

Contact me (lukas AT matt DOT wf) if you need one. As long as you pay the shipping :)

Also #1 would be extremely helpful @toto99303  .

Thanks for your work!

**Comment by toto99303** [comment]
No need for PCBs, thanks and have fun! BOM is added to the main page.
